# Docker aliases
alias dk="docker"
alias dkb="docker build . -t=$1"
alias dknet="docker network"
alias dkv="docker version"
alias dkpl="docker pull"
alias dkl="docker logs"
alias dkt="docker tag"
alias dkps="docker ps"
alias dktop="docker top"
alias dkpsa="docker ps -a"
alias dki="docker images"
alias dkip="docker inspect --format '{{.NetworkSettings.IPAddress}}'"
alias dke="docker exec -i -t"
alias dkx="docker stop"
alias dkr="docker run --rm"
alias dkrm="docker container rm"
alias dkrmi="docker image rm"
alias dkc="docker-compose"
alias dkcu="docker-compose up"
alias dkcd="docker-compose down"
